### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/photoprism-client-go#5]
we need to figure out a license for this

**Comment by lastzero** [comment]
Agree, that's important for other OSS projects to include your lib without issues.

Thanks for your contributions!

Finally had a little bit of time and added a page for your client to our docs:

https://docs.photoprism.org/developer-guide/clients/go/

**Comment by kris-nova** [comment]
oh great if we can just keep the client here then I will add an Apache2 license and we can close this.

also if you show me where the source is for the documentation I can keep it updated if/when our client grows.
